### PR TITLE
use environment variable to get the key for global filters

### LINKED ISSUE #524: sink uses the wrong key to find the global filters in the ConfigMap
the sink assumes that the `sink-filters` ConfigMap in the KubeArchive namespace will have the global filters under the key `_global` but they will actually be in under the key `kubearchive`.

This const in [`cmd/sink/filters/filters.go`](https://github.com/kubearchive/kubearchive/blob/main/cmd/sink/filters/filters.go#L26) needs to be changed to `kubearchive`

### PR DESCRIPTION
**Pull request by skoved**
## Which Issue(s) this Pull Request Resolves

Resolves #524 

## Release Note

```release-note
NONE
```

## Notes for Reviewers

Instead of using a hardcoded string for the global filters key, it can be obtained from an environment variable

### CODE REVIEW

File: cmd/sink/filters/filters.go [hunk 1]
```diff
@@ -23,12 +23,18 @@ import (
...
-	globalKey       = "kubearchive"
+	globalKeyEnvVar = "KUBEARCHIVE_NAMESPACE"
 	mountPathEnvVar = "MOUNT_PATH"
 )
 
 var ErrNoGlobal = errors.New("no global expressions exist")
 
+// getGlobalKey returns the key where global filters can be found in the sink-filters ConfigMap. Will return empty
+// string if the environment variable with the name specified by globalKeyEnvVar is not set.
+func getGlobalKey() string {
```
Comment (ggallen) [inline cmd/sink/filters/filters.go:34]: What is the advantage of having a function in this case?

File: cmd/sink/filters/filters.go [hunk 2]
```diff
@@ -283,7 +289,7 @@ func (f *Filters) handleFsEvent(event fsnotify.Event) {
 			slog.Info("Could not read global filters", "err", err)
 			break
 		}
-		if fileName == globalKey {
+		if fileName == getGlobalKey() {
```
Comment (ggallen) [inline cmd/sink/filters/filters.go:292]: Why not call this once, instead of here and 30 lines down?

File: cmd/sink/filters/filters.go (hunk 1 above)
Comment (maruiz93) [reply cmd/sink/filters/filters.go:34]: I agree that calling `os.Getenv(globalKeyEnvVar)` twice could be avoided.

Let me suggest the usage of an IIF ([Immediately Invoked Function](https://golangbyexample.com/function-golang-complete-guide/#IIF_or_Immediately_Invoked_Function))
```go
var globalKey = func() string {
    return os.Getenv(globalKeyEnvVar)
}()
```

Comment (ggallen) [reply cmd/sink/filters/filters.go:34]: > Let me suggest the usage of an IIF ([Immediately Invoked Function](https://golangbyexample.com/function-golang-complete-guide/#IIF_or_Immediately_Invoked_Function))

But I still don't see then point of a one line IIF.  Why not just call `os.Getenv` directly?

Comment (skoved) [reply cmd/sink/filters/filters.go:34]: maybe in the future we decide that `globalKey` won't get passed as an environment variable. we could just change this function instead of having to change it in 4 different places

File: cmd/sink/filters/filters.go (hunk 2 above)
Comment (skoved) [reply cmd/sink/filters/filters.go]: done

File: cmd/sink/filters/filters.go (hunk 1 above)
Comment (maruiz93) [reply cmd/sink/filters/filters.go]: also, I know that `os.Getenv` isn't a instruction that has a high cost, but I feel that it's ok to load this parameter just once. In general terms I like to prevent doing reads, even from the environment variables, if it's not needed.

Comment (skoved) [reply cmd/sink/filters/filters.go]: turns out that with Marta's suggestion as is, it the IIF can be called more than once. I moved the call to `os.Getenv` to the `init` function which Go guarantees will only be run once even if the module is imported multiple times

Comment (maruiz93) [reply cmd/sink/filters/filters.go]: interesting, I thought that it would run only once

**Review by maruiz93 — APPROVED** [review]

**Review by rh-hemartin — APPROVED** [review]

**Review by mafh314 — APPROVED** [review]
