### PR TITLE
fix sink filter test setup

### LINKED ISSUE #593: `TestHandleUpdates` in `cmd/sink/filters/filters_test.go` is not setup correctly
`TestHandleUpdates` creates multiple test cases but does not run them as separate test cases. It should call `t.Run` for each one. Additionally, it calls `newMockWatcher` which should accept a `testing.TB` and call `Helper()` to mark itself as a helper function.

### PR DESCRIPTION
**Pull request by skoved**
## Which Issue(s) this Pull Request Resolves

Resolves #593 

## Release Note

```release-note
NONE
```

## Notes for Reviewers

- `newMockWatcher` registers as a helper function
- `TestHandleUpdates` registers each of its tests as a sub-test with `t.Run`
- change variable name `testCases` -> `tests` as well as loop variable `tc` -> `tt` to be more consistent with other tests

### CODE REVIEW

File: cmd/sink/filters/filters_test.go [hunk 1]
```diff
@@ -142,40 +143,43 @@ func TestHandleUpdates(t *testing.T) {
...
+					Namespace:       "kubearchive",
+					ResourceVersion: fmt.Sprintf("%d", i),
+				},
+				Data: tt.data,
+			}
+			event := watch.Event{Type: watch.Modified, Object: &cm}
+			ch <- event
+			wg.Add(1)
+			go func(rw *toolsWatch.RetryWatcher, filter *Filters) {
+				defer wg.Done()
```
Comment (rh-hemartin) [inline cmd/sink/filters/filters_test.go:171]: In this case it does not matter, but for parallel tests, which we don't have yet, we should use `t.Cleanup` instead because defer does not guarantee order. See https://brandur.org/fragments/go-prefer-t-cleanup-with-parallel-subtests

Comment (skoved) [reply cmd/sink/filters/filters_test.go:171]: I'll make the change anyway to get myself in the right habit

Comment (skoved) [reply cmd/sink/filters/filters_test.go:171]: I _think_ this needs to remain a defer because `wg.Done` needs to be called when the `goroutine` that its in finishes not when the test it was called in completes. However, there might be something I'm missing

Comment (skoved) [reply cmd/sink/filters/filters_test.go]: but I removed the `defer` and made `wg.Done()` a direct call at the end of the function instead

**Review by maruiz93 — APPROVED** [review]

**Review by rh-hemartin — APPROVED** [review]

**Comment by skoved** [comment]
rebasing so that a merge can happen
