### PR TITLE
Fix integration test errors

### LINKED ISSUE #752: More intermitent issues on integration tests
The goal of this issue is to keep gathering problems seen on integration tests to find fixes and make them more resillient.

After https://github.com/kubearchive/kubearchive/issues/740, most of them were fixed but I've seen at least one more error on the installation phase:

- [Logs](https://github.com/kubearchive/kubearchive/actions/runs/12826696209/job/35767135850?pr=751) - Error when killing jobs because the process isn't found:

```
+ trap 'kill $(jobs -p)' EXIT
++ jobs -p
+ kill 19727
hack/kubearchive-install.sh: line 1: kill: (19727) - No such process
Error: Process completed with exit code 1.
```

- [Logs](https://github.com/kubearchive/kubearchive/actions/runs/12826448053/job/35766371043?pr=736) - Logging retrieval fails because secret credentials weren't found

```
HTTP request: /apis/batch/v1/namespaces/test-hmypwirb/cronjobs/generate-log-1/log
HTTP body: {"message":"logging secret user or password unset"}
The HTTP status returned is not OK, 400 Bad Request
```

### PR DESCRIPTION
**Pull request by maruiz93**
## Which Issue(s) this Pull Request Resolves

Resolves #752 

## Release Note

```release-note
NONE
```

## Notes for Reviewers

I'm checking in this PR how consistent are failures and adding logs to know better what is happening under the hood.

### CODE REVIEW

File: test/integration/integration_test.go [hunk 1]
```diff
@@ -540,13 +540,15 @@ func TestPagination(t *testing.T) {
 
 	url := fmt.Sprintf("https://localhost:8081/api/v1/namespaces/%s/pods", namespaceName)
 	err = retry.Do(func() error {
-		list, err := getUrl(&clientHTTP, token.Status.Token, url)
-		if err != nil {
+		list, getUrlErr := getUrl(&clientHTTP, token.Status.Token, url)
+		if getUrlErr != nil {
 			t.Fatal(err)
```
Comment (rh-hemartin) [inline test/integration/integration_test.go:545]:
```suggestion
			t.Fatal(getUrlErr)
```

**Review by rh-hemartin — APPROVED** [review]

File: test/integration/integration_test.go (hunk 1 above)
Comment (maruiz93) [reply test/integration/integration_test.go:547]: done!

File: test/integration/integration_test.go [hunk 2]
```diff
@@ -539,20 +539,24 @@ func TestPagination(t *testing.T) {
 	defer close(portForward)
 
 	url := fmt.Sprintf("https://localhost:8081/api/v1/namespaces/%s/pods", namespaceName)
+	var list *unstructured.UnstructuredList
+	var getUrlErr error
 	err = retry.Do(func() error {
-		list, err := getUrl(&clientHTTP, token.Status.Token, url)
-		if err != nil {
+		list, getUrlErr = getUrl(&clientHTTP, token.Status.Token, url)
+		if getUrlErr != nil {
```
Comment (ggallen) [inline test/integration/integration_test.go:546]: Shouldn't the next line be this?
```
t.fatal(getUrlErr)
```

Comment (maruiz93) [reply test/integration/integration_test.go:546]: yes, fixed

**Review by skoved — APPROVED** [review]
