### PR TITLE
Use slog on KubeArchive

### LINKED ISSUE #423: Implement logging using slog.
KubeArchive is currently using the standard log package for logging.  This does not provide log levels, and errors can be hard to find.  Here's an example:
```
2024/09/16 11:18:00 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp
/internal/request.(*RespWriterWrapper).writeHeader (resp_writer_wrapper.go:78)
2024/09/16 11:18:00.135948 Received cloudevent:  07d1a64b-a2b8-4391-a959-f55ef60bdf4d
2024/09/16 11:18:00.136290 Cloudevent 07d1a64b-a2b8-4391-a959-f55ef60bdf4d contains all required fields. Checking if its object ff
f80249-8dae-494d-83ed-8aa186bcc3df needs to be archived
2024/09/16 11:18:00.136350 Writing object fff80249-8dae-494d-83ed-8aa186bcc3df from cloudevent 07d1a64b-a2b8-4391-a959-f55ef60bdf4
d into the database
2024/09/16 11:18:00.137579 Failed to write object fff80249-8dae-494d-83ed-8aa186bcc3df from cloudevent 07d1a64b-a2b8-4391-a959-f55ef60bdf4d to the database: write to database failed: pq: relation "kubearchive.resource" does not exist
2024/09/16 11:18:00 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request.(*RespWriterWrapper).writeHeader (resp_writer_wrapper.go:78)
2024/09/16 11:18:00.140040 Received cloudevent:  010a72fd-8604-410b-a69c-de3c8d324976
2024/09/16 11:18:00.140293 Cloudevent 010a72fd-8604-410b-a69c-de3c8d324976 contains all required fields. Checking if its object e700ef49-146a-4dcc-8849-290c476a94df needs to be archived
2024/09/16 11:18:00.140322 Object e700ef49-146a-4dcc-8849-290c476a94df from cloudevent 010a72fd-8604-410b-a69c-de3c8d324976 does not need to be archived

```
There is an error embedded there, and it's hard to see.

We should be using slog instead, and all of the logging in KubeArchive should have a level.

### PR DESCRIPTION
**Pull request by rh-hemartin**
## Which Issue(s) this Pull Request Resolves

Resolves #423 

## Release Note

```release-note
NONE
```

## Notes for Reviewers

* I removed the logger parameter forwarding in the sink and went with using the default logger. Its simpler. If we need to pass a logger for whatever reason, then we can add it again.

### CODE REVIEW

File: cmd/api/main.go [hunk 1]
```diff
@@ -86,28 +89,30 @@ func NewServer(k8sClient kubernetes.Interface, controller routers.Controller, ca
 }
 
 func main() {
-	log.Printf("Starting KubeArchive API with version '%s', commit SHA '%s', built '%s'", version, commit, date)
+	slog.Info("Starting KubeArchive API", "version", version, "commit", commit, "built", date)
 	err := observability.Start(otelServiceName)
 	if err != nil {
-		log.Printf("Could not start opentelemetry: %s", err)
+		slog.Info("Could not start opentelemetry:", "error", err.Error())
```
Comment (ggallen) [inline cmd/api/main.go:95]: Why does this message have a colon?  None of the others seem to.

File: pkg/middleware/logging.go [hunk 2]
```diff
@@ -0,0 +1,37 @@
+// Copyright KubeArchive Authors
```
Comment (ggallen) [inline pkg/middleware/logging.go:1]: What is this package for?

File: cmd/operator/main.go [hunk 3]
```diff
@@ -7,11 +7,13 @@ import (
 	"crypto/tls"
 	"flag"
 	"log"
+	"log/slog"
 	"os"
 
 	// Import all Kubernetes client auth plugins (e.g. Azure, GCP, OIDC, etc.)
 	// to ensure that exec-entrypoint and run can make use of them.
 	_ "k8s.io/client-go/plugin/pkg/client/auth"
+	"k8s.io/klog/v2"
```
Comment (ggallen) [inline cmd/operator/main.go:16]: Why is this package added?

File: cmd/operator/main.go [hunk 4]
```diff
@@ -22,6 +24,7 @@ import (
 	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
 	"sigs.k8s.io/controller-runtime/pkg/webhook"
 
+	"github.com/go-logr/logr"
```
Comment (ggallen) [inline cmd/operator/main.go:27]: Why is this package added?

**Review by ggallen — COMMENTED** [review]
What does the format of the log messages look like?

File: pkg/middleware/logging.go (hunk 2 above)
Comment (rh-hemartin) [reply pkg/middleware/logging.go:1]: `gin` does not support `slog`, so this replaces their `Logger` middleware by our own, which uses `slog`.

File: cmd/operator/main.go (hunk 3 above)
Comment (rh-hemartin) [reply cmd/operator/main.go:16]: If we want to use `slog` on the operator we need to adapt some stuff, this package is needed because we need to configure `klog` (used by the election process) to use `slog`.

File: cmd/operator/main.go (hunk 4 above)
Comment (rh-hemartin) [reply cmd/operator/main.go:27]: Same as `klog`, we need it so we can use `slog` on internal parts of the operator.

File: cmd/api/main.go (hunk 1 above)
Comment (rh-hemartin) [reply cmd/api/main.go]: No reason, I just forgot to remove this one.

File: pkg/middleware/logging.go [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+	}
+
+	slog.Info(
+		"Served request",
+		"method", c.Request.Method,
+		"status", c.Writer.Status(),
+		"latency", latency,
+		"client", c.ClientIP(),
+		"path", path,
+		"errors", c.Errors.ByType(1).String(),
```
Comment (maruiz93) [inline pkg/middleware/logging.go:35]: Should we use `Info` method if the served request response is >= 500 with errors?

Maybe we can do something like:

```suggestion
        var logLevel int
        if c.Writer.Status() >= 500 {
		logLevel = slog.LevelError
	} else {
		logLevel = slog.LevelInfo
	}
       
	slog.Log(
	        c, logLevel,
		"Served request",
		"method", c.Request.Method,
		"status", c.Writer.Status(),
		"latency", latency,
		"client", c.ClientIP(),
		"path", path,
		"errors", c.Errors.ByType(1).String(),
```

**Review by maruiz93 — CHANGES_REQUESTED** [review]
Maybe we can address this later, but thinking of proper logs in an API Server, it's useful to have an ID for correlating the logs related to the same request.

Considering that we are making KubeArchive OpenTelemetry compatible, I guess that we could take advantage of the trace and the span when logging.

Maybe we could take advantage of the [trace.SpanFromContext function](https://pkg.go.dev/go.opentelemetry.io/otel/trace#SpanFromContext) and add it to the logged attributes.

We could do that in a slog custom Handler for the default logger that can check based on the the otel configuration (if we have it enabled or not)

File: pkg/middleware/logging.go (hunk 5 above)
Comment (rh-hemartin) [reply pkg/middleware/logging.go:35]: I think it should be the function that returns the 500 that logs at the error level. This middleware is just "neutral" information.

**Review by maruiz93 — APPROVED** [review]

**Comment by rh-hemartin** [comment]
> What does the format of the log messages look like?

```
2024/09/23 13:20:43 INFO Starting KubeArchive Sink version=v0.1.0 commit=023005ba461e47e5374e92da2e598b8dc1f4b4b3 built=2024-09-23T15:20:31+02:00
2024/09/23 13:20:43 INFO Successfully connected to the database
```

File: pkg/middleware/logging.go [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+
+func Logger(c *gin.Context) {
+	start := time.Now()
+	c.Next()
+	end := time.Now()
+
+	latency := end.Sub(start)
+	if latency > time.Minute { // Avoid very large latency number string
+		latency = latency.Truncate(time.Second)
+	}
```
Comment (beerparty) [inline pkg/middleware/logging.go:20]: You should probably be using `Round` instead of `Truncate` here.

Why are you only truncating the latency if it is more than a minute? Comparing the results is going to look weird if some of the values have nano-second accuracy and some do not. As I understand it, the default display of duration (with a "latency" label) in Go looks like this:

`latency: 1m26.550805438s`

With your conditional Truncation (or Round), you will end up comparing strings like this:

```
latency: 1m10s
latency: 26.550805438s
```

If you are worried about the final string being too long, why not shorten everything to the same precision? If you did a `latency = latency.Round(time.Millisecond)` on all values, you will truncate everything to seconds + 3 decimal points and end up with this:

```
latency: 1m10.123s
latency: 26.550s
```

**Review by beerparty — CHANGES_REQUESTED** [review]

**Review by skoved — APPROVED** [review]

File: pkg/middleware/logging.go (hunk 6 above)
Comment (rh-hemartin) [reply pkg/middleware/logging.go:20]: If we round to milisecond we loose all the microsecond precision. I prefer to remove the `Truncate` and leave it as is. Let's see how it results.

File: cmd/sink/main.go [hunk 7]
```diff
@@ -61,89 +57,107 @@ func NewSink(db database.DBInterface, logger *log.Logger, filters *filters.Filte
...
 }
 
 // Processes incoming cloudevents and writes them to the database
 func (sink *Sink) Receive(ctx context.Context, event cloudevents.Event) {
-	sink.Logger.Println("Received cloudevent: ", event.ID())
+	slog.Info("Received cloudevent", "id", event.ID())
 	k8sObj, err := models.UnstructuredFromByteSlice(event.Data())
 	if err != nil {
-		sink.Logger.Printf("Cloudevent %s is malformed and will not be processed: %s\n", event.ID(), err)
+		slog.Error("Cloudevent is malformed and will not be processed", "id", event.ID(), "err", err)
```
Comment (beerparty) [inline cmd/sink/main.go:88]: Errors indicate a failure - since you are not failing at this point, shouldn't this be a warning (`slog.Warn`) instead of an error?

File: cmd/sink/filters/filters.go [hunk 8]
```diff
@@ -248,93 +248,92 @@ func (f *Filters) deleteFiltersWithMatcher(matcher NamespaceMatcher) {
...
-		logger.Println("Creating filters for namespace:", fileName)
+		slog.Info("Creating filters for namespace", "namespace", fileName)
 		if event.Has(fsnotify.Write) {
 			err = f.updateNamespaceFilters(fileName, event.Name, globalArchive, globalDelete, globalArchiveOnDelete)
 		} else {
 			err = f.createNamespaceFilters(fileName, event.Name, globalArchive, globalDelete, globalArchiveOnDelete)
 		}
 		if err != nil {
-			logger.Printf("Problem creating filters for namespace %s: %s\n", fileName, err)
+			slog.Error("Problem creating filters for namespace", "namespace", fileName, "err", err)
```
Comment (beerparty) [inline cmd/sink/filters/filters.go:302]: Shouldn't you have an exit here? If you don't, you'll have an error message "Problem creating filters for namespace" immediately followed by an info message "Created filters for namespace". If you are going to keep processing even with this failure, I suggest you (1) make this message a warning (`slog.Warn`) and (2) put the info message in an else.

File: cmd/sink/filters/filters.go [hunk 9]
```diff
@@ -248,93 +248,92 @@ func (f *Filters) deleteFiltersWithMatcher(matcher NamespaceMatcher) {
...
+			slog.Info("Could not read global filters", "err", err)
 			break
 		}
 		if fileName == globalKey {
-			logger.Println("Creating global filters")
+			slog.Info("Creating global filters")
 			err = f.changeGlobalFilters(filePaths, globalArchive, globalDelete, globalArchiveOnDelete)
 			if err != nil {
-				logger.Println("Problem creating global filters:", err)
+				slog.Error("Problem creating global filters", "err", err)
```
Comment (beerparty) [inline cmd/sink/filters/filters.go:290]: Shouldn't you have an exit here? If you don't, you'll have an error message "Problem creating global filters" immediately followed by an info message "Successfully created global filters". If you are going to keep processing even with this failure, I suggest you (1) make this message a warning (`slog.Warn`) and (2) put the info message in an else.

**Review by beerparty — CHANGES_REQUESTED** [review]

File: cmd/sink/filters/filters.go (hunk 9 above)
Comment (rh-hemartin) [reply cmd/sink/filters/filters.go:290]: A warning will slip easier as something we don't need to pay attention to, so I think its better to have it as an error. About the logging statements themselves... @skoved

File: cmd/sink/filters/filters.go (hunk 8 above)
Comment (rh-hemartin) [reply cmd/sink/filters/filters.go:302]: A warning will slip easier as something we don't need to pay attention to, so I think its better to have it as an error. About the logging statements themselves... @skoved

File: cmd/sink/main.go (hunk 7 above)
Comment (rh-hemartin) [reply cmd/sink/main.go:88]: A warning could be understood as something we don't need to address, I don't know if here that would be true. If running we get this problem a lot and its just life, we can use Warn instead.

File: cmd/sink/filters/filters.go [hunk 10]
```diff
@@ -248,93 +248,92 @@ func (f *Filters) deleteFiltersWithMatcher(matcher NamespaceMatcher) {
...
 			err = f.updateNamespaceFilters(fileName, event.Name, globalArchive, globalDelete, globalArchiveOnDelete)
 		} else {
 			err = f.createNamespaceFilters(fileName, event.Name, globalArchive, globalDelete, globalArchiveOnDelete)
 		}
 		if err != nil {
-			logger.Printf("Problem creating filters for namespace %s: %s\n", fileName, err)
+			slog.Error("Problem creating filters for namespace", "namespace", fileName, "err", err)
 		}
-		logger.Println("Created filters for namespace:", fileName)
+		slog.Info("Created filters for namespace", "namespace", fileName)
```
Comment (beerparty) [inline cmd/sink/filters/filters.go:304]: This log message needs to go into an `else`, otherwise you will have a failure message immediately followed by a success message.

```suggestion
        else {
		    slog.Info("Created filters for namespace", "namespace", fileName)
		}
```

Comment (rh-hemartin) [reply cmd/sink/filters/filters.go]: Added

**Review by beerparty — APPROVED** [review]
