### PR TITLE
Fix deprecated usage of Defaulter and Validator webhooks

### LINKED ISSUE #749: Fix usage of webhook.Defaulter in operator as its deprecated
The `webhook.Defaulter` is deprecated and it should be updated for `webhook.CustomDefaulter` in the operator https://github.com/kubearchive/kubearchive/blob/main/cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go#L33-L33

The same applies for `webhook.Validator`

This is affecting the CI when upgrading the controller-runtime in https://github.com/kubearchive/kubearchive/pull/747

Related docs - https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation

### PR DESCRIPTION
**Pull request by maruiz93**
## Which Issue(s) this Pull Request Resolves

Resolves #749 

## Release Note

```release-note
NONE
```

## Notes for Reviewers

Replaced webhook.Validator with webhook.CustomValidator
Replaced webhook.Defaulter with webhook.CustomDeafulter
Renamed private method validateCELExpressions to validateKAC so it can also allocate the name validation
to avoid having this piece repeated.

Everything was done by following the kubebuilder docs  of the webhook implementation - https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation

With this effort unit tests were also added for the custom defaulter and validator

### CODE REVIEW

**Comment by maruiz93** [comment]
Still in progress, webhooks aren't being exposed right now

**Comment by maruiz93** [comment]
> Still in progress, webhooks aren't being exposed right now

Fixed

**Review by rh-hemartin — APPROVED** [review]

File: cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go [hunk 1]
```diff
@@ -13,65 +14,86 @@ import (
...
-// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
-func (kac *KubeArchiveConfig) ValidateCreate() (admission.Warnings, error) {
-	kubearchiveconfiglog.Info("validate create", "namespace", kac.Namespace, "name", kac.Name)
+var _ webhook.CustomValidator = &KubeArchiveConfigCustomValidator{}
 
-	if kac.Name != kubearchiveResourceName {
-		return nil, fmt.Errorf("The KubeArchiveConfig resource must be named '%s'.", kubearchiveResourceName)
+// ValidateCreate implements webhook.CustomValidator so a webhook will be registered for the type
+func (kaccv *KubeArchiveConfigCustomValidator) ValidateCreate(
+	_ context.Context, obj runtime.Object) (admission.Warnings, error) {
```
Comment (skoved) [inline cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go:57]: This is a nit, but I think this would be easier to read if the function declaration can't fit on one line

```suggestion
func (kaccv *KubeArchiveConfigCustomValidator) ValidateCreate(
	_ context.Context, obj runtime.Object,
) (admission.Warnings, error) {
```

File: cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go [hunk 2]
```diff
@@ -13,65 +14,86 @@ import (
...
 
-// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
-func (kac *KubeArchiveConfig) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
-	kubearchiveconfiglog.Info("validate update", "namespace", kac.Namespace, "name", kac.Name)
-
-	if kac.Name != kubearchiveResourceName {
-		return nil, fmt.Errorf("Cannot update KubeArchiveConfig resource named '%s'.", kubearchiveResourceName)
+// ValidateUpdate implements webhook.CustomValidator so a webhook will be registered for the type
+func (kaccv *KubeArchiveConfigCustomValidator) ValidateUpdate(
+	_ context.Context, _ runtime.Object, new runtime.Object) (admission.Warnings, error) {
```
Comment (skoved) [inline cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go:69]: This is a nit, but I think this would be easier to read if the function declaration can't fit on one line

```suggestion
func (kaccv *KubeArchiveConfigCustomValidator) ValidateUpdate(
	_ context.Context, _ runtime.Object, new runtime.Object,
) (admission.Warnings, error) {
```

File: cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go [hunk 3]
```diff
@@ -13,65 +14,86 @@ import (
...
 
-	return kac.validateCELExpressions()
+	return kaccv.validateKAC(kac)
 }
 
-// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
-func (kac *KubeArchiveConfig) ValidateDelete() (admission.Warnings, error) {
+// ValidateDelete implements webhook.CustomValidator so a webhook will be registered for the type
+func (kaccv *KubeArchiveConfigCustomValidator) ValidateDelete(
+	_ context.Context, new runtime.Object) (admission.Warnings, error) {
```
Comment (skoved) [inline cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go:81]: This is a nit, but I think this would be easier to read if the function declaration can't fit on one line

```suggestion
func (kaccv *KubeArchiveConfigCustomValidator) ValidateDelete(
	_ context.Context, new runtime.Object,
) (admission.Warnings, error) {
```

**Review by skoved — APPROVED** [review]
These are just formatting nits. Everything else looks good :+1:

File: cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go (hunk 1 above)
Comment (maruiz93) [reply cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go]: agree! fixed

File: cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go (hunk 3 above)
Comment (maruiz93) [reply cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go]: agree! fixed

File: cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go (hunk 2 above)
Comment (maruiz93) [reply cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go]: agree! fixed
